const bookMapping = [
    { index: 0, name: "Genesis", abbrev: "gn" },
    { index: 1, name: "Exodus", abbrev: "ex" },
    { index: 2, name: "Leviticus", abbrev: "lv" },
    { index: 3, name: "Numbers", abbrev: "nm" },
    { index: 4, name: "Deuteronomy", abbrev: "dt" },
    { index: 5, name: "Joshua", abbrev: "js" },
    { index: 6, name: "Judges", abbrev: "jg" },
    { index: 7, name: "Ruth", abbrev: "rt" },
    { index: 8, name: "1 Samuel", abbrev: "1s" },
    { index: 9, name: "2 Samuel", abbrev: "2s" },
    { index: 10, name: "1 Kings", abbrev: "1k" },
    { index: 11, name: "2 Kings", abbrev: "2k" },
    { index: 12, name: "1 Chronicles", abbrev: "1ch" },
    { index: 13, name: "2 Chronicles", abbrev: "2ch" },
    { index: 14, name: "Ezra", abbrev: "ez" },
    { index: 15, name: "Nehemiah", abbrev: "nh" },
    { index: 16, name: "Esther", abbrev: "es" },
    { index: 17, name: "Job", abbrev: "jb" },
    { index: 18, name: "Psalms", abbrev: "ps" },
    { index: 19, name: "Proverbs", abbrev: "pr" },
    { index: 20, name: "Ecclesiastes", abbrev: "ec" },
    { index: 21, name: "Song of Solomon", abbrev: "ss" },
    { index: 22, name: "Isaiah", abbrev: "is" },
    { index: 23, name: "Jeremiah", abbrev: "jr" },
    { index: 24, name: "Lamentations", abbrev: "lm" },
    { index: 25, name: "Ezekiel", abbrev: "ek" },
    { index: 26, name: "Daniel", abbrev: "dn" },
    { index: 27, name: "Hosea", abbrev: "hs" },
    { index: 28, name: "Joel", abbrev: "jl" },
    { index: 29, name: "Amos", abbrev: "am" },
    { index: 30, name: "Obadiah", abbrev: "ob" },
    { index: 31, name: "Jonah", abbrev: "jh" },
    { index: 32, name: "Micah", abbrev: "mi" },
    { index: 33, name: "Nahum", abbrev: "na" },
    { index: 34, name: "Habakkuk", abbrev: "hk" },
    { index: 35, name: "Zephaniah", abbrev: "zp" },
    { index: 36, name: "Haggai", abbrev: "hg" },
    { index: 37, name: "Zechariah", abbrev: "zc" },
    { index: 38, name: "Malachi", abbrev: "ml" },
    { index: 39, name: "Matthew", abbrev: "mt" },
    { index: 40, name: "Mark", abbrev: "mk" },
    { index: 41, name: "Luke", abbrev: "lk" },
    { index: 42, name: "John", abbrev: "jo" },
    { index: 43, name: "Acts", abbrev: "ac" },
    { index: 44, name: "Romans", abbrev: "rm" },
    { index: 45, name: "1 Corinthians", abbrev: "1co" },
    { index: 46, name: "2 Corinthians", abbrev: "2co" },
    { index: 47, name: "Galatians", abbrev: "gl" },
    { index: 48, name: "Ephesians", abbrev: "ep" },
    { index: 49, name: "Philippians", abbrev: "ph" },
    { index: 50, name: "Colossians", abbrev: "cl" },
    { index: 51, name: "1 Thessalonians", abbrev: "1th" },
    { index: 52, name: "2 Thessalonians", abbrev: "2th" },
    { index: 53, name: "1 Timothy", abbrev: "1ti" },
    { index: 54, name: "2 Timothy", abbrev: "2ti" },
    { index: 55, name: "Titus", abbrev: "ti" },
    { index: 56, name: "Philemon", abbrev: "pm" },
    { index: 57, name: "Hebrews", abbrev: "hb" },
    { index: 58, name: "James", abbrev: "jm" },
    { index: 59, name: "1 Peter", abbrev: "1pe" },
    { index: 60, name: "2 Peter", abbrev: "2pe" },
    { index: 61, name: "1 John", abbrev: "1jo" },
    { index: 62, name: "2 John", abbrev: "2jo" },
    { index: 63, name: "3 John", abbrev: "3jo" },
    { index: 64, name: "Jude", abbrev: "jd" },
    { index: 65, name: "Revelation", abbrev: "rv" }
];

module.exports = bookMapping;
